# Generated by Django 4.0.3 on 2022-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=5)),
                ('atomic_no', models.IntegerField()),
                ('mass_no', models.FloatField()),
                ('group', models.IntegerField()),
                ('kind', models.CharField(max_length=30)),
            ],
        ),
    ]
