# Generated by Django 4.0.3 on 2022-04-09 10:35

from django.db import migrations
import csv
import os
from django.db import transaction
from django.db import IntegrityError
from dotenv import load_dotenv

load_dotenv()

def load(apps, schema_editor):
  Elements = apps.get_model('elements', 'Elements')
  
  f = open(os.getenv('file'))
  reader = csv.reader(f)
  
  for element, symbol, atomic, mass, group, kind in reader:
    try:
      with transaction.atomic():
        record = Elements(element=element, symbol=symbol, atomic_no=atomic, mass_no=mass, group=group, kind=kind)
        record.save()
    except IntegrityError:
      record.delete()
      
    
  f.close()
  
def reverse_load(apps, schema_editor):
  Elements = apps.get_model('elements', 'Elements')
  Elements.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
      migrations.RunPython(load, reverse_load),
    ]
