# Generated by Django 4.0.3 on 2022-05-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20220409_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_no', models.CharField(max_length=200)),
                ('element', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('atomic_mass', models.CharField(max_length=200)),
                ('neurons', models.CharField(max_length=200)),
                ('protons', models.CharField(max_length=200)),
                ('Electrons', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=200)),
                ('radioactive', models.BooleanField()),
                ('natural', models.BooleanField()),
                ('metal', models.BooleanField()),
                ('Nonmetal', models.BooleanField()),
                ('matalloid', models.BooleanField()),
                ('kind', models.CharField(max_length=200)),
                ('atomic_radius', models.CharField(max_length=200)),
                ('eletro_negativity', models.CharField(max_length=200)),
                ('ionization_Energy', models.CharField(max_length=200)),
                ('Density', models.CharField(max_length=200)),
                ('Melting_point', models.CharField(max_length=200)),
                ('Boiling_point', models.CharField(max_length=200)),
                ('isotopes', models.CharField(max_length=200)),
                ('discoverer', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('specific_heat', models.CharField(max_length=200)),
                ('shells', models.CharField(max_length=200)),
                ('valence_electron', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
