# Generated by Django 4.0.3 on 2022-06-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_allelements_constants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allelements',
            old_name='matalloid',
            new_name='metalloid',
        ),
    ]
