# Generated by Django 4.0.3 on 2022-06-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_auto_20220523_2154'),
        ('elements', '0004_rename_matalloid_allelements_metalloid'),
    ]

    operations = [
    ]
