# Generated by Django 4.0.3 on 2022-06-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_merge_20220607_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allelements',
            name='eletro_negativity',
            field=models.FloatField(null=True),
        ),
    ]
