# Generated by Django 4.0.3 on 2022-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_alter_allelements_eletro_negativity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allelements',
            name='Melting_point',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='specific_heat',
            field=models.FloatField(null=True),
        ),
    ]
