# Generated by Django 4.0.3 on 2022-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0007_alter_allelements_melting_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allelements',
            name='valence_electron',
            field=models.IntegerField(null=True),
        ),
    ]
