# Generated by Django 4.0.3 on 2022-06-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0008_alter_allelements_valence_electron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allelements',
            name='Electrons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='atomic_mass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='atomic_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='atomic_radius',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='ionization_Energy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='isotopes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='neurons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='protons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='shells',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
