# Generated by Django 4.0.3 on 2022-06-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0009_alter_allelements_electrons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allelements',
            name='Boiling_point',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='Density',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='Electrons',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='Melting_point',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='atomic_mass',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='atomic_no',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='atomic_radius',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='discoverer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='element',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='eletro_negativity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='group',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='ionization_Energy',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='isotopes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='kind',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='neurons',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='period',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='phase',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='protons',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='shells',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='specific_heat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='symbol',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='valence_electron',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='allelements',
            name='year',
            field=models.CharField(default='', max_length=200),
        ),
    ]
