# Generated by Django 4.0.3 on 2022-06-07 14:12

from django.db import migrations, models
import elements.models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0010_alter_allelements_boiling_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mug_shot', models.ImageField(upload_to=elements.models.path)),
                ('project_key', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=300)),
            ],
        ),
    ]
