# Generated by Django 4.0.3 on 2022-06-13 20:47

from django.db import migrations, models
import elements.models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0012_users_secrete_key_alter_users_mug_shot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mug_shot',
            field=models.ImageField(null=True, upload_to=elements.models.path),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='project_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='users',
            name='secrete_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
