# Generated by Django 4.0.3 on 2022-06-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0014_rename_secrete_key_users_secret_key_users_acc_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_age',
            field=models.CharField(default='06/16/2022, 09:55:07', max_length=200),
        ),
    ]
