# Generated by Django 4.0.3 on 2022-07-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_no', models.CharField(default='', max_length=200)),
                ('element', models.CharField(default='', max_length=200)),
                ('symbol', models.CharField(default='', max_length=200)),
                ('atomic_mass', models.CharField(default='', max_length=200)),
                ('neurons', models.CharField(default='', max_length=200)),
                ('protons', models.CharField(default='', max_length=200)),
                ('Electrons', models.CharField(default='', max_length=200)),
                ('period', models.CharField(default='', max_length=200)),
                ('group', models.CharField(default='', max_length=200)),
                ('phase', models.CharField(default='', max_length=200)),
                ('radioactive', models.BooleanField()),
                ('natural', models.BooleanField()),
                ('metal', models.BooleanField()),
                ('Nonmetal', models.BooleanField()),
                ('metalloid', models.BooleanField()),
                ('kind', models.CharField(default='', max_length=200)),
                ('atomic_radius', models.CharField(default='', max_length=200)),
                ('eletro_negativity', models.CharField(default='', max_length=200)),
                ('ionization_Energy', models.CharField(default='', max_length=200)),
                ('Density', models.CharField(default='', max_length=200)),
                ('Melting_point', models.CharField(default='', max_length=200)),
                ('Boiling_point', models.CharField(default='', max_length=200)),
                ('isotopes', models.CharField(default='', max_length=200)),
                ('discoverer', models.CharField(default='', max_length=200)),
                ('year', models.CharField(default='', max_length=200)),
                ('specific_heat', models.CharField(default='', max_length=200)),
                ('shells', models.CharField(default='', max_length=200)),
                ('valence_electron', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('spin', models.CharField(max_length=100)),
                ('charge', models.CharField(max_length=100)),
                ('mass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('uncertainty', models.CharField(max_length=100)),
            ],
        ),
    ]
