# Generated by Django 4.1 on 2022-09-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalConstant',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('constant', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('atomic_no', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('element', models.CharField(default='', max_length=200)),
                ('symbol', models.CharField(default='', max_length=200)),
                ('atomic_mass', models.CharField(default='', max_length=200)),
                ('neurons', models.CharField(default='', max_length=200)),
                ('protons', models.CharField(default='', max_length=200)),
                ('electrons', models.CharField(default='', max_length=200)),
                ('period', models.CharField(default='', max_length=200)),
                ('group', models.CharField(default='', max_length=200)),
                ('phase', models.CharField(default='', max_length=200)),
                ('radioactive', models.BooleanField()),
                ('natural', models.BooleanField()),
                ('metal', models.BooleanField()),
                ('nonmetal', models.BooleanField()),
                ('metalloid', models.BooleanField()),
                ('kind', models.CharField(default='', max_length=200)),
                ('atomic_radius', models.CharField(default='', max_length=200)),
                ('eletro_negativity', models.CharField(default='', max_length=200)),
                ('ionization_Energy', models.CharField(default='', max_length=200)),
                ('density', models.CharField(default='', max_length=200)),
                ('melting_point', models.CharField(default='', max_length=200)),
                ('boiling_point', models.CharField(default='', max_length=200)),
                ('isotopes', models.CharField(default='', max_length=200)),
                ('discoverer', models.CharField(default='', max_length=200)),
                ('year', models.CharField(default='', max_length=200)),
                ('specific_heat', models.CharField(default='', max_length=200)),
                ('shells', models.CharField(default='', max_length=200)),
                ('valence_electron', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('particle', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('spin', models.CharField(max_length=100)),
                ('charge', models.CharField(max_length=100)),
                ('mass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalConstant',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('constant', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('uncertainty', models.CharField(max_length=100)),
            ],
        ),
    ]
