# Generated by Django 4.1 on 2022-08-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220725_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhysicalConstant',
        ),
    ]
