# Generated by Django 4.1 on 2022-09-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220928_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalconstant',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='element',
            name='discoverer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='element',
            name='year',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='particle',
            name='kind',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='particle',
            name='mass',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='physicalconstant',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
