# Generated by Django 4.1 on 2022-09-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_chemicalconstant_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='radioactive',
            field=models.BooleanField(null=True),
        ),
    ]
