# Generated by Django 4.1 on 2022-08-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_physicalconstant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('uncertainty', models.CharField(max_length=100)),
            ],
        ),
    ]
