# Generated by Django 4.1 on 2022-09-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_element_radioactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='metal',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='metalloid',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='natural',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='nonmetal',
            field=models.BooleanField(null=True),
        ),
    ]
